# goals finetuning no pretrain
USERNAME: 'rockfor'
DATA:
  BASEPATH: "/mnt/mass_storage/master_ai/retinal_oct_dataset_collection/GOALS"
  NUM_WORKERS: 5
  DATASET: "goals"
  IMG_SIZE: [800, 1100]
  TRAIN_DATASET_SUBSET_K: -1
  OVERSAMPLE_TRAIN_DATASET_FACTOR: 100

MODEL:
  NUM_CLASSES: 6
  NAME: "unet"
  PRETRAINED: false
  # RESUME_PATH: "/home/parting/master_AI/medical_ai/Fundus-OCT-challenge/output/models/basicunet_combined_pretrain_recon0_04197.ckpt"
  # FREEZE_ENCODER: true

TRAIN:
  EPOCHS: 200
  TRAIN_BATCH_SIZE: 4
  VAL_BATCH_SIZE: 4
  ACCUMUALTE_GRAD_BATCHES: 2
  TASK: "segmentation"
  LR: 0.001 # higher learning rate because it's a convnet
  LOG_FREQ_VAL: 4
  LOG_FREQ_TRAIN: 5
  SEPARATE_BOTTOM_BG: false
  NO_TRANSFORMS: false
  NO_SPTRANSFORMS: false
  RUN_NAME: "exp: transforms - all transform - basicunet"