# basic example config

DATA:
  BASEPATH: "C:\\Users\\Ana\\Master\\MedicalAI\\Fundus-OCT-challenge\\GOALS"
  NUM_WORKERS: 5

MODEL:
  NAME: "deeplab"
  PRETRAINED: true

TRAIN:
  EPOCHS: 20
  TRAIN_BATCH_SIZE: 2
  VAL_BATCH_SIZE : 2
  TASK: 'curriculum'

