# basic example config
USERNAME: 'rockfor'
DATA:
  BASEPATH: "/mnt/mass_storage/master_ai/retinal_oct_dataset_collection/GOALS"
  NUM_WORKERS: 5

MODEL:
  NAME: "deeplab"
  PRETRAINED: true

TRAIN:
  EPOCHS: 20
  TRAIN_BATCH_SIZE: 2
  VAL_BATCH_SIZE : 2

