# config that finetunes on goals using pretrained weights from the large combined dataset on the reconstruction task

DATA:
  BASEPATH: "/mnt/mass_storage/master_ai/retinal_oct_dataset_collection"
  NUM_WORKERS: 5
  DATASET: "combined"
  IMG_SIZE: [800, 1100]

MODEL:
  NAME: "unetr"
  PRETRAINED: true
  NUM_CLASSES_CLASSIFICATION: 5

TRAIN:
  EPOCHS: 500
  TRAIN_BATCH_SIZE: 1
  VAL_BATCH_SIZE : 1
  TASK : "reconstruction"
  LOG_FREQ : 10
  LOG_FREQ_IMG : 50
  ACCUMUALTE_GRAD_BATCHES: 6
  MAX_EPOCH_LENGTH : 3000
  LR : 0.001