# config that finetunes on goals using pretrained weights from the large combined dataset on the reconstruction task
USERNAME: 'rockfor'
DATA:
  BASEPATH: "/mnt/mass_storage/master_ai/retinal_oct_dataset_collection/GOALS"
  NUM_WORKERS: 5
  DATASET: "goals"
  IMG_SIZE: [800, 1100]

MODEL:
  NAME: "unet"
  PRETRAINED: true
  RESUME_PATH: "/home/parting/master_AI/medical_ai/Fundus-OCT-challenge/data/models/simple_unet_recon_combined_11epochs.ckpt"
  NUM_CLASSES_CLASSIFICATION: 5

TRAIN:
  EPOCHS: 500
  TRAIN_BATCH_SIZE: 6
  VAL_BATCH_SIZE : 1
  TASK : "segmentation"
  LOG_FREQ_TRAIN : 25
  LOG_FREQ_VAL : 10