# basic example config
USERNAME: 'rockfor'
DATA:
  BASEPATH: "/mnt/mass_storage/master_ai/retinal_oct_dataset_collection"
  NUM_WORKERS: 5
  DATASET: "combined"
  IMG_SIZE: [800, 1100]

MODEL:
  NUM_CLASSES: 6
  NAME: "unet"
  PRETRAINED: true

TRAIN:
  EPOCHS: 200
  TRAIN_BATCH_SIZE: 4
  VAL_BATCH_SIZE: 4
  ACCUMUALTE_GRAD_BATCHES: 2
  TASK: 'reconstruction'
  LR: 0.001
  LOG_FREQ_VAL: 50
  LOG_FREQ_TRAIN: 50
  MAX_EPOCH_LENGTH : 2000
  SEPARATE_BOTTOM_BG: false