# config that finetunes on goals using pretrained weights from the large combined dataset on the reconstruction task
USERNAME: 'rockfor'
DATA:
  BASEPATH: "/mnt/mass_storage/master_ai/retinal_oct_dataset_collection/GOALS"
  NUM_WORKERS: 5
  DATASET: "goals"
  IMG_SIZE: [800, 1100]

MODEL:
  NUM_CLASSES: 6
  NAME: "unetr"
  PRETRAINED: true

TRAIN:
  EPOCHS: 200
  TRAIN_BATCH_SIZE: 1
  VAL_BATCH_SIZE: 1
  ACCUMUALTE_GRAD_BATCHES: 8
  TASK: "segmentation"
  LR: 0.0001
  LOG_FREQ_VAL: 4
  LOG_FREQ_TRAIN: 10
  SEPARATE_BOTTOM_BG: false